# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###
POST http://localhost:8000/users/
Content-Type: application/json

{"username": "testuser", "email": "test@example.com", "full_name": "Test User"}

###

GET http://localhost:8000/users/id/1
###
GET http://localhost:8000/users/email/test@example.com
###
GET localhost:8000/users/